
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Nurlan Rustamov
 */
public class DosyaEndirme extends javax.swing.JFrame {

    private int sayi = 0;

    /**
     * Creates new form DosyaEndırme
     */
    public DosyaEndirme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DownloadProgress = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dosya Endirmek");
        setBounds(new java.awt.Rectangle(400, 400, 0, 0));

        DownloadProgress.setStringPainted(true);

        jButton1.setText("Dosya Endırmenı Basladın...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(DownloadProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jButton1)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(DownloadProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Timer timer = new Timer(50, null);//null, əsasən bir dəyişənin əvvəlki qiyməti və ya bir obyekt referansının atanmadığı vəziyyətlər üçün istifadə olunur.
        timer.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
//            1. ornek yoxlamaq ucun
//                System.out.println("Salam"); 
//            2. ornek burda bir problem olacaq siz bunu calisdirin ve probleme 3. ornekden davam edin.
                /* sayi++;
                DownloadProgress.setValue(sayi);
                if (DownloadProgress.getValue() == 100) {
//       burada this dediyimiz zaman anonim class içərisindəki ActionListener-i oxumağa çalışır. ancaq bu this bizim ana class-ı oxuması lazım. 92. setir             
//                    JOptionPane.showMessageDialog(this, sayi);
                    JOptionPane.showMessageDialog(DosyaEndirme.this, "Dosya endirmeniz tamamland;");
                    setVisible(false);// frame-i yox etmek
                }
                 */
                //                System.out.println("Salam"); 
//            3. ornek 
/*
                sayi++;
                DownloadProgress.setValue(sayi);
                if (DownloadProgress.getValue() == 100) {
//       burada this dediyimiz zaman anonim class içərisindəki ActionListener-i oxumağa çalışır. ancaq bu this bizim ana class-ı oxuması lazım. 92. setir             
//                    JOptionPane.showMessageDialog(this, sayi);
                    JOptionPane.showMessageDialog(DosyaEndirme.this, "Dosya endirmeniz tamamland;");
                    timer.stop();
                    System.exit(0);

                }
                 */
                //            4. ornek KecidSehifesine kecmek
                sayi++;
                DownloadProgress.setValue(sayi);
                if (DownloadProgress.getValue() == 100) {
                    timer.stop();
                    KecidSehife kecid = new KecidSehife();
                    setVisible(false);
                    kecid.setVisible(true);

                }
            }
        });
        timer.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DosyaEndirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DosyaEndirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DosyaEndirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DosyaEndirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DosyaEndirme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar DownloadProgress;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
