
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Nurlan Rustamov
 */
public class StokGuncelle extends javax.swing.JFrame {

    /**
     * Creates new form StokGuncelle
     */
    public StokGuncelle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MalAdiTextField = new javax.swing.JTextField();
        Cb_Categories = new javax.swing.JComboBox<>();
        QiymetTextField = new javax.swing.JTextField();
        MesajLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        StokTable = new javax.swing.JTable();
        Click = new javax.swing.JButton();
        GuncelButton = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mal adi:");

        jLabel2.setText("Kategoriyalar:");

        jLabel3.setText("Qiymet:");

        Cb_Categories.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yaglar", "Sasisqalar", "Sular", " " }));

        MesajLabel.setForeground(new java.awt.Color(255, 51, 51));

        StokTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mal Adi:", "Kategoriya:", "Qiymet:"
            }
        ));
        StokTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StokTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(StokTable);

        Click.setText("Mal Elave Et");
        Click.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickActionPerformed(evt);
            }
        });

        GuncelButton.setText("Malinizi guncelleyin");
        GuncelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuncelButtonActionPerformed(evt);
            }
        });

        DeleteBtn.setText("Mehsul Sil");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MesajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MalAdiTextField)
                            .addComponent(Cb_Categories, 0, 116, Short.MAX_VALUE)
                            .addComponent(QiymetTextField))
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Click, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GuncelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(DeleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MalAdiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Click))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cb_Categories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuncelButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QiymetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteBtn))
                .addGap(38, 38, 38)
                .addComponent(MesajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClickActionPerformed
        // TODO add your handling code here:
        MesajLabel.setText("");//mesaj yazimiz
        DefaultTableModel model = (DefaultTableModel) StokTable.getModel();
        if (MalAdiTextField.getText().trim().equals("")) {
            MesajLabel.setText("Malin adi bos ola bilmez!");
        } else {
            Object[] elaveEdilecekler = {MalAdiTextField.getText(), Cb_Categories.getSelectedItem().toString(), QiymetTextField.getText()};
            model.addRow(elaveEdilecekler);
        }
    }//GEN-LAST:event_ClickActionPerformed

    private void GuncelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuncelButtonActionPerformed
        // TODO add your handling code here:
        MesajLabel.setText("");
        DefaultTableModel model = (DefaultTableModel) StokTable.getModel();
        int secilmis_Row = StokTable.getSelectedRow();
        if (secilmis_Row == -1) {
            if (StokTable.getRowCount() == 0) {
                MesajLabel.setText("Stok bos ola bilmez!!!");
            }
            MesajLabel.setText("Xahis olunur guncellenecek bir mal secin");
        } else {
            model.setValueAt(MalAdiTextField.getText(), secilmis_Row, 0);
            model.setValueAt(Cb_Categories.getSelectedItem().toString(), secilmis_Row, 1);
            model.setValueAt(QiymetTextField.getText(), secilmis_Row, 2);
        }
    }//GEN-LAST:event_GuncelButtonActionPerformed

    private void StokTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StokTableMouseClicked
        // TODO add your handling code here:
        int seciliRow = StokTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) StokTable.getModel();
        MalAdiTextField.setText(model.getValueAt(seciliRow, 0).toString());
        Cb_Categories.setSelectedItem(model.getValueAt(seciliRow, 1).toString());
        QiymetTextField.setText(model.getValueAt(seciliRow, 2).toString());

    }//GEN-LAST:event_StokTableMouseClicked

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        MesajLabel.setText("");
        DefaultTableModel model = (DefaultTableModel) StokTable.getModel();
        int seciliRow = StokTable.getSelectedRow();
        if (seciliRow == -1) {
            if (StokTable.getRowCount() == 0) {
                MesajLabel.setText("Ürün tablosu hal-hazırda boş...");
            } else {
                MesajLabel.setText("Xahiş olunur silinecek bir ürün seçin...");
            }
        } else {
            model.removeRow(seciliRow);
            MesajLabel.setText("Silindi!!!");
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StokGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StokGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StokGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StokGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StokGuncelle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cb_Categories;
    private javax.swing.JButton Click;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton GuncelButton;
    private javax.swing.JTextField MalAdiTextField;
    private javax.swing.JLabel MesajLabel;
    private javax.swing.JTextField QiymetTextField;
    private javax.swing.JTable StokTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
